### ISSUE TITLE
Tweak the HTTP server to allow autodetection of range requests

### ISSUE THREAD

**Issue by lenormf** [ergoithz/browsepy#11]
Hi,

I regularly play videos directly off of the `browsepy` web interface using `mpv`, and I have to use the `--force-seekable` option everytime to be able to seek into the file, e.g. `mpv --force-seekable http://192.168.1.3/open/videos/foo.mp4`. I'm not sure how `mpv` tries to verify that the server can handle `Range` header fields, but it's definitely supported, isn't there anything that can be done from the API side to let video players autodetect it?

Thanks.

**Comment by ergoithz** [comment]
Hi,
thank you for taking your time writting this issue.

Browsepy uses flask's send_file to serve files from disk, and it probably handles **Range** requests on most common cases, without being guaranteed at all as it depends on OS and wsgi server.

In the other hand, to notify this functionality to HTTP clients, **/open/&lt;path:path&gt;** (and probably **/download/file/&lt;path:path&gt;**) must expose the **Accept-Ranges: bytes** HTTP header (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges). This cannot be achieved via configuration at the moment, but only using the current plugin API.

The PluginManager instance passed to every plugin **register_plugin** function (see http://ergoithz.github.io/browsepy/plugins.html#protocol) exposes browsepy's flask object via its **app** attribute, where you can do stuff like overwritting endpoints or attaching your own **after_request** hook (see http://flask.pocoo.org/docs/0.12/api/#flask.Flask.after_request), in order to return said **Accept-Ranges** header.
